### ISSUE TITLE
AdaptiveThreshold C input restricted

### ISSUE THREAD

**Issue by tom131313** [WPIRoboticsProjects/GRIP#490] opened 2016-02-07 23:25 UTC
AdaptiveThreshold C value input is restricted to positive numbers, if typing input.  The "decrement arrow" allows negative C values and the OpenCV documentation says negative C values are possible.

**Comment by ThomasJClark** [comment] 2016-02-08 21:38
Duplicate of #329

**Closed by ThomasJClark** 2016-02-08 21:38 UTC
