### ISSUE TITLE
GRIP closes when more than 1 IP cameras are added

### ISSUE THREAD

**Issue by anon-raizer** [WPIRoboticsProjects/GRIP#918] opened 2019-01-26 02:03 UTC
After adding a 2nd or 3rd IP camera, grip closes all by itself, but if I only use 1 IP camera it works fine.

**Comment by JLLeitschuh** [comment] 2019-01-28 15:53
Is there a log/exception you can share with us?

**Comment by JLLeitschuh** [comment] 2019-01-29 16:11
@SamCarlberg If you get a second, can you test this?

**Comment by SamCarlberg** [comment] 2019-04-20 21:11
Cannot reproduce locally. Closing since no further information is forthcoming.

**Closed by SamCarlberg** 2019-04-20 21:11 UTC
