### ISSUE TITLE
Sudden termination using mjpeg streamer from coprocessor

### ISSUE THREAD

**Issue by kjm16216** [WPIRoboticsProjects/GRIP#808] opened 2017-01-28 00:17 UTC
I am working in GRIP 1.5.1, Win10, using a Pi3B coprocessor with mjpeg streamer.
I am building a filter in Windows, and when I put the IP Camera source for the mjpeg stream, GRIP comes to a sudden termination.

gist log 
https://gist.github.com/kjm16216/ad438f3efd6f1e2d11c53557da7f80c2

I can upload the GRIP file too if that's helpful.

**Comment by SamCarlberg** [comment] 2017-01-28 01:40
Duplicate of #794

**Closed by SamCarlberg** 2017-01-28 01:40 UTC
Labels: type: duplicate
