### ISSUE TITLE
Building from source on a Raspberry Pi

### ISSUE THREAD

**Issue by ajfreed00** [WPIRoboticsProjects/GRIP#389] opened 2016-01-19 20:10 UTC
So the problem is basically this right here. I'm running it on a Raspberry Pi 2 Model B with Raspbian Jessie. What am I doing wrong?

```
Note: in order to honour the org.gradle.jvmargs and/or org.gradle.java.home values specified for this build, it is necessary to fork a new JVM.
To avoid the slowdown associated with this extra process, you might want to consider running Gradle with the daemon enabled.
Please see the user guide chapter on the daemon at http://gradle.org/docs/1.5/userguide/gradle_daemon.html.
:buildSrc:clean
:buildSrc:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:buildSrc:extractSources UP-TO-DATE
:buildSrc:compileGroovy
:buildSrc:processResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Could not copy file '/home/pi/Downloads/GRIP-1.0.0/buildSrc/src/main/resources/META-INF' to '/home/pi/Downloads/GRIP-1.0.0/buildSrc/build/resources/main/META-INF'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5 mins 6.102 secs
```

**Comment by ajfreed00** [comment] 2016-01-19 20:11
Oops, the title is wrong on this. xD

**Comment by JLLeitschuh** [comment] 2016-01-19 20:13
JavaFX does not work on a PI because it is not included in ARM Java.

**Comment by ajfreed00** [comment] 2016-01-19 20:14
Oh ok thanks. Does GRIP work at all on any Windows 32 bit systems?

**Comment by JLLeitschuh** [comment] 2016-01-19 20:18
Yes, there are downloads on the release page.
You can also build from source if you wish and it should work as well.

For anyone who wants to work on this in the future we may be able to provide a release that uses the openJDK for a pi release.
https://www.linkedin.com/pulse/oracle-just-removed-javafx-support-arm-jan-snelders
I have no idea how complicated that would be.
I'm sure we could probably get travis to build with the openJDK automatically.

**Comment by ajfreed00** [comment] 2016-01-19 20:22
Well, there is a bit of another problem... Whenever I try to install the
last "stable" release of GRIP, the installer says my Windows is not
compatible. I'm running Windows 10 x32, is that a problem?

On Tue, Jan 19, 2016 at 2:18 PM, Jonathan Leitschuh <
notifications@github.com> wrote:

> Yes, there are downloads on the release page.
> You can also build from source if you wish and it should work as well.
>
> For anyone who wants to work on this in the future we may be able to
> provide a release that uses the openJDK for a pi release.
>
> https://www.linkedin.com/pulse/oracle-just-removed-javafx-support-arm-jan-snelders
> I have no idea how complicated that would be.
> I'm sure we could probably get travis to build with the openJDK
> automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPIRoboticsProjects/GRIP/issues/389#issuecomment-172973654>
> .
>



-- 
Thanks,
Alexander Freed
ajfreed00@gmail.com

**Comment by ThomasJClark** [comment] 2016-01-19 20:48
> Well, there is a bit of another problem... Whenever I try to install the
> last "stable" release of GRIP, the installer says my Windows is not
> compatible. I'm running Windows 10 x32, is that a problem?

Which installer are you using?  If you're not on a 64 bit machine, make sure it's `grip-1.0.0-x86.exe`

**Comment by ajfreed00** [comment] 2016-01-19 20:57
Lol, I don't know if something got changed or what, but the first Windows
installer didn't say x86 OR x64. It was just grip-1.0.0.exe. xD Now I'm
installing the RIGHT one. Lol thanks for your help, guys!

On Tue, Jan 19, 2016 at 2:48 PM, Thomas Clark <notifications@github.com>
wrote:

> Well, there is a bit of another problem... Whenever I try to install the
> last "stable" release of GRIP, the installer says my Windows is not
> compatible. I'm running Windows 10 x32, is that a problem?
>
> Which installer are you using? If you're not on a 64 bit machine, make
> sure it's grip-1.0.0-x86.exe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPIRoboticsProjects/GRIP/issues/389#issuecomment-172982113>
> .
>



-- 
Thanks,
Alexander Freed
ajfreed00@gmail.com

**Comment by ThomasJClark** [comment] 2016-01-19 20:59
Yeah, there was originally only a 64 bit build.  I added the `-x86` and `-x64` suffixes later

**Comment by JLLeitschuh** [comment] 2016-01-27 21:50
I think this is a duplicate of #366
I'm going to close this issue and direct people to that issue in the future.

**Closed by JLLeitschuh** 2016-01-27 21:50 UTC
Labels: OS: unsupported OS, PR's Please!, type: build, type: duplicate
