### ISSUE TITLE
Create an appveyor build plan that "fakes out" being on a 32 bit system

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#807] opened 2017-01-27 23:54 UTC
I think that if we just create another build and fake out being in a 32 bit environment the build system will create the correct artifact even though its building on a 64 bit system.

It will probably just require changing some of the build logic.

**Comment by SamCarlberg** [comment] 2017-01-29 04:12
Duplicate of #612

**Closed by SamCarlberg** 2017-01-29 04:12 UTC
Labels: type: build, type: duplicate
