### ISSUE TITLE
Resize not working in Ubuntu

### ISSUE THREAD

**Issue by PaulaRudy** [WPIRoboticsProjects/GRIP#69] opened 2015-11-03 18:14 UTC
I can full screen and minimize but not resize the window manually. The split screen is working however.

**Comment by ThomasJClark** [comment] 2015-11-14 04:38
I can't reproduce this as of v0.1.0 on a fresh VM with Ubuntu 15.10.  You were probably right - it's a problem with computer.

**Comment by PaulaRudy** [comment] 2015-11-15 17:35
Still an issue here. It happens after I open a source image or  webcam, even if "cancel"ed. Before I try to add a source the resize works.

**Comment by JLLeitschuh** [comment] 2016-01-04 01:31
Are you still experiencing this problem??

**Comment by PaulaRudy** [comment] 2016-01-05 20:20
Yes.

**Comment by PaulaRudy** [comment] 2016-01-10 21:53
I've been poking around with this but I'm at a loss here. Any suggestions?

**Comment by JLLeitschuh** [comment] 2016-01-27 21:10
I think this is taken care of. I'm going to close this.

**Closed by JLLeitschuh** 2016-01-27 21:10 UTC
Labels: help wanted, os: Linux, type: bug
